### ISSUE TITLE
Prod: Router throws a 404 on refresh

### ISSUE THREAD

**Issue by JesseNoseworthy** [colindamelio/saraswati#40]
**Describe the bug**

In Production, `React-Router` throws a 404 on refresh.

**To Reproduce**
1. Go to [prod](http://www.saraswatibali.com)
2. Navigate to any route
3. Refresh the page
4. Observe a 404 page

**Expected behavior**
The page refreshes

**Comment by johnathanfong** [comment]
I mentioned this to @colindamelio already, but right now the `error` message when someone clicks `Apply Now` is really awkward, esp since this CTA is our number 1 priority right now. I definitely think the fix to prevent routes from breaking on refresh is great, but we'll need to update these landing page CTAs to redirect to the `APPLY` page, or to have a better long-term fix.

cc @JesseNoseworthy

**Comment by johnathanfong** [comment]
This has been fixed! (Along with some other small styling bugs I noticed).
